CREATE TABLE IF NOT EXISTS users (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  lastName VARCHAR(100) NOT NULL,
  email VARCHAR(254) NOT NULL UNIQUE,
  password VARCHAR(60) NOT NULL,
  createdAt TIMESTAMP DEFAULT NOW(),
  updatedAt TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gains (
  id UUID NOT NULL PRIMARY KEY,
  ownerId UUID NOT NULL,
  value DECIMAL NOT NULL,
  createdAt TIMESTAMP DEFAULT NOW(),
  updatedAt TIMESTAMP DEFAULT NOW(),
  CONSTRAINT FK_OWNER
    FOREIGN KEY(ownerId)
      REFERENCES users(id)
      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS categories (
  id UUID NOT NULL PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  createdAt TIMESTAMP DEFAULT NOW(),
  updatedAt TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS expenses (
  id UUID NOT NULL PRIMARY KEY,
  ownerId UUID NOT NULL,
  categoryId UUID NOT NULL,
  description VARCHAR(200) NOT NULL,
  cost DECIMAL NOT NULL,
  paidAt TIMESTAMP,
  createdAt TIMESTAMP DEFAULT NOW(),
  updatedAt TIMESTAMP DEFAULT NOW(),
  CONSTRAINT FK_OWNER
    FOREIGN KEY(ownerId)
      REFERENCES users(id)
      ON DELETE CASCADE,

  CONSTRAINT FK_CATEGORY
    FOREIGN KEY(ownerId)
      REFERENCES categories(id)
      ON DELETE CASCADE
);
