ALTER TABLE users 
  ALTER COLUMN createdAt TYPE TIMESTAMPTZ,
  ALTER COLUMN updatedAt TYPE TIMESTAMPTZ;

ALTER TABLE expenses 
  ALTER COLUMN createdAt TYPE TIMESTAMPTZ,
  ALTER COLUMN updatedAt TYPE TIMESTAMPTZ;

ALTER TABLE gains 
  ALTER COLUMN createdAt TYPE TIMESTAMPTZ,
  ALTER COLUMN updatedAt TYPE TIMESTAMPTZ;

ALTER TABLE categories 
  ALTER COLUMN createdAt TYPE TIMESTAMPTZ,
  ALTER COLUMN updatedAt TYPE TIMESTAMPTZ;

ALTER TABLE migrations
  ALTER COLUMN executed_at TYPE TIMESTAMPTZ
